### ISSUE TITLE
CMakeLists.txt: fix qmake invokation

### ISSUE THREAD

**Issue by velnias75** [velnias75/QGitHubReleaseAPI#2]
Fix qmake invokation if both Qt4 and Qt5 are installed.

**Comment by ikorolev93** [comment]
Use `${Qt5Core_QMAKE_EXECUTABLE}` instead of hardcoding `qmake`? You'll have to `find_package(Qt5Core)` for that.

**Comment by velnias75** [comment]
Using `${Qt5Core_QMAKE_EXECUTABLE}` breaks Debian/Ubuntu builds.
